name: cantara
version: '2.2.3'
summary: A Song Presentation Software.
description: |
  A simple, leightweight but powerful program for song presentation in churches, small groups or at karaoke parties.
confinement: devmode
base: core22
grade: stable

architectures:
  - build-on: amd64

parts:
  cantara:
    plugin: nil
    source: .
    source-type: local
    build-packages:
    - fpc
    - lazarus
    - lcl
    - lcl-utils
    - build-essential
    - libqt5pas-dev
    - libqt5pas1
    stage-packages:
    - libqt5pas-dev
    - libqt5pas1
    override-build: |
      lazbuild -B Cantara.lpi --ws=qt5
      install -d -m 755 $SNAPCRAFT_PART_INSTALL/languages/de/
      install -s -m 755 languages/de/cantara.mo $SNAPCRAFT_PART_INSTALL/languages/de/cantara.mo
      install -s -m 755 cantara $SNAPCRAFT_PART_INSTALL/cantara
      install -s -m 755 cantara.desktop $SNAPCRAFT_PART_INSTALL/cantara.desktop
      install -s -m 755 Cantara.ico $SNAPCRAFT_PART_INSTALL/Cantara.ico
      install -s -m 755 Cantara.png $SNAPCRAFT_PART_INSTALL/Cantara.png
    stage:
    - cantara
    - languages
    - cantara.desktop
    - Cantara.ico
    - Cantara.png

apps:
  cantara:
    command: cantara
    desktop: cantara.desktop
    plugs:
    - home
    - desktop
    - desktop-legacy
    - x11
