name: cantara
version: '2.2.3'
summary: A Song Presentation Software.
description: |
  A simple, leightweight but powerful program for song presentation in churches, small groups or at karaoke parties.
confinement: devmode
base: core20
grade: stable

architectures:
  - build-on: amd64

parts:
  cantara:
    plugin: dump
    source: https://github.com/reckel-jm/cantara/releases/download/v2.2.3beta/cantara-2.2.3-x86.tar.gz
    stage-packages:
    # Autodetected dependencies
    - libqt5pas-dev

apps:
  cantara:
    command: cantara
    desktop: cantara.desktop
    plugs:
    - home
    - desktop
    - desktop-legacy
    - x11
