name: cantara
version: '2.2.3'
summary: A Song Presentation Software.
description: |
  A simple, leightweight but powerful program for song presentation in churches, small groups or at karaoke parties.
confinement: devmode
base: core20
grade: stable

architectures:
  - build-on: amd64

parts:
  cantara:
    plugin: nil
    source: .
    source-type: local
    build-packages:
    - fpc
    - lazarus
    - lcl
    - lcl-utils
    - build-essential
    - libqt5pas-dev
    - libqt5pas1
    stage-packages:
    - libqt5pas-dev
    - libqt5pas1
    - libatk1.0-0
    - libcairo2
    - libdatrie1
    - libfribidi0
    - libgdk-pixbuf2.0-0
    - libgtk2.0-0
    - libpango-1.0-0
    - libpangocairo-1.0-0
    - libpangoft2-1.0-0
    - libpixman-1-0
    - libthai0
    - libxcomposite1
    - libxcursor1
    - libxdamage1
    - libxi6
    - libxinerama1
    - libxrandr2
    override-build: |
      lazbuild -B Cantara.lpi --ws=qt5
      cp -r languages $SNAPCRAFT_PART_INSTALL/
      install cantara $SNAPCRAFT_PART_INSTALL/
      install cantara.desktop $SNAPCRAFT_PART_INSTALL/
      install Cantara.ico $SNAPCRAFT_PART_INSTALL/
      install Cantara.png $SNAPCRAFT_PART_INSTALL/
    stage:
    - lib
    - usr
    - etc
    - cantara
    - languages
    - cantara.desktop
    - Cantara.ico
    - Cantara.png

apps:
  cantara:
    command: cantara
    desktop: cantara.desktop
    plugs:
    - home
    - desktop
    - desktop-legacy
    - x11
