name: cantara
version: '2.2.3'
summary: A Song Presentation Software.
description: |
  A simple, leightweight but powerful program for song presentation in churches, small groups or at karaoke parties.
confinement: devmode
base: core22
grade: stable

architectures:
  - build-on: amd64

parts:
  cantara:
    plugin: nil
    source: .
    source-type: local
    build-packages:
    - fpc
    - lazarus
    - lcl
    - lcl-utils
    - build-essential
    - libqt5pas-dev
    - libqt5pas1
    stage-packages:
    - libqt5pas
    - libqt5pas1
    override-build: |
      lazbuild -B Cantara.lpi --ws=qt5
    stage:
    - cantara
    - languages/de/cantara.mo
    - cantara.desktop
    - Cantara.ico
    - Cantara.png

apps:
  cantara:
    command: cantara
    desktop: cantara.desktop
    plugs:
    - home
    - desktop
    - desktop-legacy
    - x11
