name: cantara
version: '2.2.3'
summary: A Song Presentation Software.
description: |
  A simple, leightweight but powerful program for song presentation in churches, small groups or at karaoke parties.
confinement: strict
icon: Cantara.png
base: core22
grade: stable

architectures:
  - build-on: amd64

parts:
  cantara:
    plugin: nil
    source: .
    source-type: local
    build-packages:
    - fpc
    - lazarus
    - lcl
    - lcl-utils
    - build-essential
    - libqt5pas-dev
    - libqt5pas1
    build-snaps:
    - qt5-core22
    stage-packages:
    - libqt5pas-dev
    - libqt5pas1
    - libatk1.0-0
    - libcairo2
    - libdatrie1
    - libfribidi0
    - libgdk-pixbuf2.0-0
    - libgtk2.0-0
    - libpango-1.0-0
    - libpangocairo-1.0-0
    - libpangoft2-1.0-0
    - libpixman-1-0
    - libthai0
    - libxcomposite1
    - libxcursor1
    - libxdamage1
    - libxi6
    - libxinerama1
    - libxrandr2
    override-build: |
      lazbuild -B Cantara.lpi --ws=qt5
      cp -r languages $SNAPCRAFT_PART_INSTALL/
      install cantara $SNAPCRAFT_PART_INSTALL/
      install cantara.desktop $SNAPCRAFT_PART_INSTALL/
      install Cantara.ico $SNAPCRAFT_PART_INSTALL/
      install Cantara.png $SNAPCRAFT_PART_INSTALL/
    stage:
    - lib
    - usr
    - etc
    - cantara
    - languages
    - cantara.desktop
    - Cantara.ico
    - Cantara.png
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - cantara
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - qt5-core22
    override-prime: |
      set -eux
      for snap in "qt5-core22"; do  # List all content-snaps and base snaps you're using here
          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done

apps:
  cantara:
    command: cantara
    desktop: cantara.desktop
    plugs:
    - home
    - opengl
    - desktop
    - desktop-legacy
    - x11
    extensions:
    - kde-neon
