on:
  push:
    branches:
      - master  # Set a branch to deploy

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [windows-latest,ubuntu-latest,macos-latest]
        lazarus-versions: [stable]
    steps:
    - uses: actions/checkout@v2
    - uses: gcarreno/setup-lazarus@v3.2
      with:
        lazarus-version: "stable"
        #include-packages: "lib"
        with-cache: false
    - name: Build the Windows Application:
      if: ${{ matrix.operating-system != 'windows-latest' }}
      run: lazbuild -B Cantara.lpi
    - name: Install libqt5pas dependency under Ubuntu:
      if: ${{ matrix.operating-system != 'ubuntu-latest' }}
      run: sudo apt install libqtpas
    - name: Build the Linux Application:
      if: ${{ matrix.operating-system != 'ubuntu-latest' }}
      run: lazbuild -B Cantara.lpi --ws=qt5
    - name: Build the MacOS Application:
      if: ${{ matrix.operating-system != 'macos-latest' }}
      run: lazbuild -B Cantara.lpi
