steps:
- uses: actions/checkout@v2
- uses: gcarreno/setup-lazarus@v3.2
  with:
    lazarus-version: "stable"
    #include-packages: "lib"
    with-cache: true
- run: lazbuild Cantara.lpi --ws=qt5
# - run: YourTestProject
