on:
  push:
    branches:
      - master  # Set a branch to deploy

jobs:
  build:
  runs-on: ubuntu-22.04
    strategy:
      cantara:
        operating-system: [windows-latest,ubuntu-latest,macos-latest]
        lazarus-versions: stable
  steps:
  - uses: actions/checkout@v2
  - uses: gcarreno/setup-lazarus@v3.2
    with:
      lazarus-version: "stable"
      #include-packages: "lib"
      with-cache: true
  - run: lazbuild Cantara.lpi --ws=qt5
  # - run: YourTestProject
